### ISSUE TITLE
license for com.solacesystems:sol-jcsmp 

### ISSUE THREAD

**Issue by shanghaimoonlight** [SolaceProducts/spring-cloud-stream-binder-solace#20]
We use this spring-cloud-stream-binder-solace in our application which has APACHE 2.0 license. But the library com.solacesystems:sol-jcsmp this binder uses has a "SOLACE CORPORATION LICENSE AGREEMENT"
https://mvnrepository.com/artifact/com.solacesystems/sol-jcsmp/10.6.3

Can you clarify whether we can still use  spring-cloud-stream-binder-solace  under APACHE 2.0 license?

**Comment by a-masse** [comment]
You must agree to the SOLACE CORPORATION LICENSE AGREEMENT to use the Solace JCSMP API which is included in spring-cloud-stream-binder-solace
