### ISSUE TITLE
Consider removing spring-cloud-starter-stream-solace

### ISSUE THREAD

**Issue by snicoll** [SolaceProducts/spring-cloud-stream-binder-solace#21]
A starter that brings a single jar is a bit unusual, we usually avoid that. This is particularly relevant for Spring Cloud Stream as binder implementations are provided in the form of a unique jar (which you're already doing in this project as far as I understand) so having a separate starter is not really necessary. 

Have I missed something?

**Comment by Mrc0113** [comment]
Discussed and decided not to do. Closing
