### ISSUE TITLE
Support client usernames which don't have queue creation permissions

### ISSUE THREAD

**Issue by Nephery** [SolaceProducts/spring-cloud-stream-binder-solace#24]
Applications using the binder fails to start if the client profile or the client username is not allowed to create endpoints.

We should investigate if its possible to add a way for application developers to skip queue provisioning.

**Comment by PhilippeKhalife** [comment]
Fixed, thanks @Nephery - Available in new repository https://github.com/SolaceProducts/solace-spring-cloud/tree/master/solace-spring-cloud-starters/solace-spring-cloud-stream-starter
