### ISSUE TITLE
Compatibility with Spring Integration Core 5.1.0

### ISSUE THREAD

**Issue by MarkRobbo** [SolaceProducts/spring-cloud-stream-binder-solace#9]
Currently due to repackages of classes such as AcknowledgmentCallback / AcknowledgmentCallbackFactory from `org.springframework.integration.support` to `org.springframework.integration.acks` (and probably more) this cloud binder is no longer compatible with the newest version of Spring Boot (and Spring Cloud release candidate).

To reproduce use the following dependencies along with spring-cloud-stream-binder-solace 1.0.0:
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.1.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-stream-dependencies</artifactId>
                <version>Fishtown.RC2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by michalchng** [comment]
Hi Mark,

Thanks for notifying us of this. We will investigate this compatibility issue. 

Regards,

Michael

**Comment by MarkRobbo** [comment]
Please note that in a few weeks this compatibility issue will mean that the binder is no longer compatible with the latest release version of Spring Cloud Stream.

> As it stands now this should be the final Release Candidate before General Availability release 2.0.0.RELEASE in several weeks.

Source: https://spring.io/blog/2018/11/19/spring-cloud-stream-fishtown-rc2-2-1-0-rc2-release-announcement

**Comment by panterose** [comment]
As noted by Mark, this means the Solace Binder blocks from upgrading to https://spring.io/blog/2019/01/08/announcing-general-availability-of-spring-cloud-stream-fishtown-release-2-1-0-release

**Comment by khamlaoui** [comment]
Hello,
Do you have any idea about when this issue will be fixed? 
Thanks in advance

**Comment by Nephery** [comment]
Thanks for the PR! I'll look into the issue soon.

**Comment by khamlaoui** [comment]
Hello, Do you have an idea please of when you will merge the PR?

**Comment by PhilippeKhalife** [comment]
PR Merged.
